language: ruby
before_install: gem install bundler

rvm:
  - 1.9.3
  - 2.0.0

branches:
  only:
    - master
    - production

notifications:
  email:
    recipients:
      - api-versions@erichmenge.com
env:
  - RAILS_VERSION=3.0.20
  - RAILS_VERSION=3.1.12
  - RAILS_VERSION=3.2.13
  - RAILS_VERSION=master

matrix:
  allow_failures:
    - env: RAILS_VERSION=master
