language: ruby
before_install: gem install bundler

rvm:
  - 1.9.3
  - 2.0.0

branches:
  only:
    - master
    - production

notifications:
  email:
    recipients:
      - api-versions@erichmenge.com
env:
  - RAILS_VERSION=3.0.17
  - RAILS_VERSION=3.1.8
  - RAILS_VERSION=3.2.9
  - RAILS_VERSION=master

matrix:
  allow_failures:
    - rvm: 1.9.3
      env: RAILS_VERSION=master
    - rvm: 2.0.0
      env: RAILS_VERSION=master
