language: ruby

rvm:
  - 1.9.3
  - 2.0.0

notifications:
  email:
    recipients:
      - api-versions@erich.erichmenge.com
env:
  - RAILS_VERSION=3-0-stable
  - RAILS_VERSION=3-1-stable
  - RAILS_VERSION=3-2-stable
